services:
  - type: web
    name: printq-backend
    env: node
    plan: standard
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GMAIL_USER
        scope: secret
      - key: GMAIL_PASSWORD
        scope: secret